---
atom_feed:
  hide: true
baseurl: /research-blog
collections:
  posts:
    output: true
  publications:
    output: true
defaults:
  - scope:
      path: ''
      type: pages
    values:
      analytics: true
      author_profile: true
      layout: splash
include:
  - _data
  - _pages
  - _publications
logo: /assets/images/horizontal_logo.png
minimal_mistakes_skin: zenseact_beige
name: Zenseact
plugins:
  - jekyll-include-cache
  - jekyll-scholar
# Build settings
repository: zenseact/research-blog
remote_theme: mmistakes/minimal-mistakes@4.24.0
title: Zenseact Research
url: https://zenseact.github.io